// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: mus.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MusType int32

const (
	MusType_CustomData MusType = 0
	MusType_IdleData   MusType = 1
)

// Enum value maps for MusType.
var (
	MusType_name = map[int32]string{
		0: "CustomData",
		1: "IdleData",
	}
	MusType_value = map[string]int32{
		"CustomData": 0,
		"IdleData":   1,
	}
)

func (x MusType) Enum() *MusType {
	p := new(MusType)
	*p = x
	return p
}

func (x MusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MusType) Descriptor() protoreflect.EnumDescriptor {
	return file_mus_proto_enumTypes[0].Descriptor()
}

func (MusType) Type() protoreflect.EnumType {
	return &file_mus_proto_enumTypes[0]
}

func (x MusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MusType.Descriptor instead.
func (MusType) EnumDescriptor() ([]byte, []int) {
	return file_mus_proto_rawDescGZIP(), []int{0}
}

// a protocol define a set of reuqest and responses
type MusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type MusType `protobuf:"varint,1,opt,name=type,proto3,enum=MusType" json:"type,omitempty"`
}

func (x *MusRequest) Reset() {
	*x = MusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mus_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MusRequest) ProtoMessage() {}

func (x *MusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mus_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MusRequest.ProtoReflect.Descriptor instead.
func (*MusRequest) Descriptor() ([]byte, []int) {
	return file_mus_proto_rawDescGZIP(), []int{0}
}

func (x *MusRequest) GetType() MusType {
	if x != nil {
		return x.Type
	}
	return MusType_CustomData
}

type MusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code uint32 `protobuf:"varint,1,opt,name=Code,json=code,proto3" json:"Code,omitempty"`
	// Code indicates the result of this transfer
	MuHash string   `protobuf:"bytes,2,opt,name=mu_hash,json=muHash,proto3" json:"mu_hash,omitempty"`
	Name   []string `protobuf:"bytes,3,rep,name=name,proto3" json:"name,omitempty"`
	U      []string `protobuf:"bytes,4,rep,name=u,proto3" json:"u,omitempty"`
}

func (x *MusResponse) Reset() {
	*x = MusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mus_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MusResponse) ProtoMessage() {}

func (x *MusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mus_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MusResponse.ProtoReflect.Descriptor instead.
func (*MusResponse) Descriptor() ([]byte, []int) {
	return file_mus_proto_rawDescGZIP(), []int{1}
}

func (x *MusResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MusResponse) GetMuHash() string {
	if x != nil {
		return x.MuHash
	}
	return ""
}

func (x *MusResponse) GetName() []string {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *MusResponse) GetU() []string {
	if x != nil {
		return x.U
	}
	return nil
}

var File_mus_proto protoreflect.FileDescriptor

var file_mus_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x0a, 0x4d,
	0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e, 0x4d, 0x75, 0x73, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x5c, 0x0a, 0x0b, 0x4d, 0x75, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x75,
	0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x75, 0x48,
	0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x75, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x01, 0x75, 0x2a, 0x27, 0x0a, 0x07, 0x4d, 0x75, 0x73, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x10, 0x00,
	0x12, 0x0c, 0x0a, 0x08, 0x49, 0x64, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x10, 0x01, 0x42, 0x07,
	0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mus_proto_rawDescOnce sync.Once
	file_mus_proto_rawDescData = file_mus_proto_rawDesc
)

func file_mus_proto_rawDescGZIP() []byte {
	file_mus_proto_rawDescOnce.Do(func() {
		file_mus_proto_rawDescData = protoimpl.X.CompressGZIP(file_mus_proto_rawDescData)
	})
	return file_mus_proto_rawDescData
}

var file_mus_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mus_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mus_proto_goTypes = []interface{}{
	(MusType)(0),        // 0: MusType
	(*MusRequest)(nil),  // 1: MusRequest
	(*MusResponse)(nil), // 2: MusResponse
}
var file_mus_proto_depIdxs = []int32{
	0, // 0: MusRequest.type:type_name -> MusType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mus_proto_init() }
func file_mus_proto_init() {
	if File_mus_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mus_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mus_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mus_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mus_proto_goTypes,
		DependencyIndexes: file_mus_proto_depIdxs,
		EnumInfos:         file_mus_proto_enumTypes,
		MessageInfos:      file_mus_proto_msgTypes,
	}.Build()
	File_mus_proto = out.File
	file_mus_proto_rawDesc = nil
	file_mus_proto_goTypes = nil
	file_mus_proto_depIdxs = nil
}
