// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: p2p.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// designed to be shared between all app protocols
type MessageData struct {
	// shared between all requests
	ClientVersion        string   `protobuf:"bytes,1,opt,name=clientVersion,proto3" json:"clientVersion,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	NodeId               string   `protobuf:"bytes,3,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	NodePubKey           []byte   `protobuf:"bytes,4,opt,name=nodePubKey,proto3" json:"nodePubKey,omitempty"`
	Sign                 []byte   `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty"`
	Timestamp            int64    `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Gossip               bool     `protobuf:"varint,7,opt,name=gossip,proto3" json:"gossip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageData) Reset()         { *m = MessageData{} }
func (m *MessageData) String() string { return proto.CompactTextString(m) }
func (*MessageData) ProtoMessage()    {}
func (*MessageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{0}
}
func (m *MessageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageData.Unmarshal(m, b)
}
func (m *MessageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageData.Marshal(b, m, deterministic)
}
func (m *MessageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageData.Merge(m, src)
}
func (m *MessageData) XXX_Size() int {
	return xxx_messageInfo_MessageData.Size(m)
}
func (m *MessageData) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageData.DiscardUnknown(m)
}

var xxx_messageInfo_MessageData proto.InternalMessageInfo

func (m *MessageData) GetClientVersion() string {
	if m != nil {
		return m.ClientVersion
	}
	return ""
}

func (m *MessageData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageData) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *MessageData) GetNodePubKey() []byte {
	if m != nil {
		return m.NodePubKey
	}
	return nil
}

func (m *MessageData) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *MessageData) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MessageData) GetGossip() bool {
	if m != nil {
		return m.Gossip
	}
	return false
}

// a protocol define a set of reuqest and responses
type WritefileRequest struct {
	// Roothash uniquely identifies a user data
	Roothash string `protobuf:"bytes,1,opt,name=Roothash,json=roothash,proto3" json:"Roothash,omitempty"`
	// Datahash is the currently written data hash value
	Datahash string `protobuf:"bytes,2,opt,name=Datahash,json=datahash,proto3" json:"Datahash,omitempty"`
	// Data is the data written this time
	Data []byte `protobuf:"bytes,3,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
	// MessageData is a generic message
	MessageData *MessageData `protobuf:"bytes,4,opt,name=messageData,proto3" json:"messageData,omitempty"`
	// Offset is the offset of this write
	Offset int64 `protobuf:"varint,5,opt,name=Offset,json=offset,proto3" json:"Offset,omitempty"`
	// Length is the length of the data written this time
	Length               uint32   `protobuf:"varint,6,opt,name=Length,json=length,proto3" json:"Length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WritefileRequest) Reset()         { *m = WritefileRequest{} }
func (m *WritefileRequest) String() string { return proto.CompactTextString(m) }
func (*WritefileRequest) ProtoMessage()    {}
func (*WritefileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{1}
}
func (m *WritefileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WritefileRequest.Unmarshal(m, b)
}
func (m *WritefileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WritefileRequest.Marshal(b, m, deterministic)
}
func (m *WritefileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WritefileRequest.Merge(m, src)
}
func (m *WritefileRequest) XXX_Size() int {
	return xxx_messageInfo_WritefileRequest.Size(m)
}
func (m *WritefileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WritefileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WritefileRequest proto.InternalMessageInfo

func (m *WritefileRequest) GetRoothash() string {
	if m != nil {
		return m.Roothash
	}
	return ""
}

func (m *WritefileRequest) GetDatahash() string {
	if m != nil {
		return m.Datahash
	}
	return ""
}

func (m *WritefileRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *WritefileRequest) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *WritefileRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *WritefileRequest) GetLength() uint32 {
	if m != nil {
		return m.Length
	}
	return 0
}

type WritefileResponse struct {
	// MessageData is a generic message
	MessageData *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	// Offset is the write offset the receiver wants
	Offset int64 `protobuf:"varint,2,opt,name=Offset,json=offset,proto3" json:"Offset,omitempty"`
	// Code indicates the result of this transfer
	Code                 uint32   `protobuf:"varint,3,opt,name=Code,json=code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WritefileResponse) Reset()         { *m = WritefileResponse{} }
func (m *WritefileResponse) String() string { return proto.CompactTextString(m) }
func (*WritefileResponse) ProtoMessage()    {}
func (*WritefileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{2}
}
func (m *WritefileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WritefileResponse.Unmarshal(m, b)
}
func (m *WritefileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WritefileResponse.Marshal(b, m, deterministic)
}
func (m *WritefileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WritefileResponse.Merge(m, src)
}
func (m *WritefileResponse) XXX_Size() int {
	return xxx_messageInfo_WritefileResponse.Size(m)
}
func (m *WritefileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WritefileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WritefileResponse proto.InternalMessageInfo

func (m *WritefileResponse) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *WritefileResponse) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *WritefileResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

// a protocol define a set of reuqest and responses
type ReadfileRequest struct {
	// Roothash uniquely identifies a user data
	Roothash string `protobuf:"bytes,1,opt,name=Roothash,json=roothash,proto3" json:"Roothash,omitempty"`
	// Datahash is the currently written data hash value
	Datahash string `protobuf:"bytes,2,opt,name=Datahash,json=datahash,proto3" json:"Datahash,omitempty"`
	// MessageData is a generic message
	MessageData *MessageData `protobuf:"bytes,3,opt,name=messageData,proto3" json:"messageData,omitempty"`
	// Offset is the offset that the reader wants to read
	Offset               int64    `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadfileRequest) Reset()         { *m = ReadfileRequest{} }
func (m *ReadfileRequest) String() string { return proto.CompactTextString(m) }
func (*ReadfileRequest) ProtoMessage()    {}
func (*ReadfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{3}
}
func (m *ReadfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadfileRequest.Unmarshal(m, b)
}
func (m *ReadfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadfileRequest.Marshal(b, m, deterministic)
}
func (m *ReadfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadfileRequest.Merge(m, src)
}
func (m *ReadfileRequest) XXX_Size() int {
	return xxx_messageInfo_ReadfileRequest.Size(m)
}
func (m *ReadfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadfileRequest proto.InternalMessageInfo

func (m *ReadfileRequest) GetRoothash() string {
	if m != nil {
		return m.Roothash
	}
	return ""
}

func (m *ReadfileRequest) GetDatahash() string {
	if m != nil {
		return m.Datahash
	}
	return ""
}

func (m *ReadfileRequest) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *ReadfileRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type ReadfileResponse struct {
	// Data is the returned data
	Data []byte `protobuf:"bytes,1,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
	// MessageData is a generic message
	MessageData *MessageData `protobuf:"bytes,2,opt,name=messageData,proto3" json:"messageData,omitempty"`
	// Offset is the data offset returned by the peer
	Offset int64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// Code indicates the result of this transfer
	Code uint32 `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	// Length is the returned data length
	Length               uint32   `protobuf:"varint,5,opt,name=length,proto3" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadfileResponse) Reset()         { *m = ReadfileResponse{} }
func (m *ReadfileResponse) String() string { return proto.CompactTextString(m) }
func (*ReadfileResponse) ProtoMessage()    {}
func (*ReadfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{4}
}
func (m *ReadfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadfileResponse.Unmarshal(m, b)
}
func (m *ReadfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadfileResponse.Marshal(b, m, deterministic)
}
func (m *ReadfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadfileResponse.Merge(m, src)
}
func (m *ReadfileResponse) XXX_Size() int {
	return xxx_messageInfo_ReadfileResponse.Size(m)
}
func (m *ReadfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadfileResponse proto.InternalMessageInfo

func (m *ReadfileResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ReadfileResponse) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *ReadfileResponse) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ReadfileResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ReadfileResponse) GetLength() uint32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func init() {
	proto.RegisterType((*MessageData)(nil), "MessageData")
	proto.RegisterType((*WritefileRequest)(nil), "WritefileRequest")
	proto.RegisterType((*WritefileResponse)(nil), "WritefileResponse")
	proto.RegisterType((*ReadfileRequest)(nil), "ReadfileRequest")
	proto.RegisterType((*ReadfileResponse)(nil), "ReadfileResponse")
}

func init() { proto.RegisterFile("p2p.proto", fileDescriptor_e7fdddb109e6467a) }

var fileDescriptor_e7fdddb109e6467a = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x3f, 0x6b, 0xdb, 0x40,
	0x14, 0xe7, 0x24, 0x59, 0x96, 0x9f, 0xed, 0xd6, 0xbd, 0xa1, 0x88, 0x52, 0x8a, 0x10, 0x1d, 0x34,
	0xa9, 0xe0, 0x8e, 0xdd, 0xda, 0x2e, 0x21, 0x09, 0x09, 0x37, 0x24, 0x90, 0x4d, 0xf6, 0x3d, 0xcb,
	0x07, 0xb6, 0x4e, 0xd1, 0x9d, 0x87, 0x7c, 0x8c, 0xac, 0xf9, 0x30, 0xd9, 0xf2, 0xbd, 0xc2, 0x3d,
	0x2b, 0xb6, 0x6c, 0x08, 0x78, 0xc8, 0xa6, 0xdf, 0xef, 0x1d, 0xfc, 0xfe, 0x21, 0x18, 0xd4, 0xd3,
	0x3a, 0xaf, 0x1b, 0x6d, 0x75, 0xfa, 0xc2, 0x60, 0x78, 0x89, 0xc6, 0x14, 0x25, 0xfe, 0x2f, 0x6c,
	0xc1, 0x7f, 0xc2, 0x78, 0xbe, 0x52, 0x58, 0xd9, 0x1b, 0x6c, 0x8c, 0xd2, 0x55, 0xcc, 0x12, 0x96,
	0x0d, 0xc4, 0x21, 0xc9, 0x3f, 0x81, 0xa7, 0x64, 0xec, 0xd1, 0xc9, 0x53, 0x92, 0x7f, 0x85, 0xb0,
	0xd2, 0x12, 0xcf, 0x64, 0xec, 0x13, 0xd7, 0x22, 0xfe, 0x03, 0xc0, 0x7d, 0x5d, 0x6f, 0x66, 0xe7,
	0xf8, 0x10, 0x07, 0x09, 0xcb, 0x46, 0xa2, 0xc3, 0x70, 0x0e, 0x81, 0x51, 0x65, 0x15, 0xf7, 0xe8,
	0x42, 0xdf, 0xfc, 0x3b, 0x0c, 0xac, 0x5a, 0xa3, 0xb1, 0xc5, 0xba, 0x8e, 0xc3, 0x84, 0x65, 0xbe,
	0xd8, 0x13, 0x4e, 0xa9, 0xd4, 0xc6, 0xa8, 0x3a, 0xee, 0x27, 0x2c, 0x8b, 0x44, 0x8b, 0xd2, 0x67,
	0x06, 0x93, 0xdb, 0x46, 0x59, 0x5c, 0xa8, 0x15, 0x0a, 0xbc, 0xdf, 0xa0, 0xb1, 0xfc, 0x1b, 0x44,
	0x42, 0x6b, 0xbb, 0x2c, 0xcc, 0xb2, 0xcd, 0x11, 0x35, 0x2d, 0x76, 0x37, 0x17, 0x98, 0x6e, 0xdb,
	0x20, 0x91, 0x6c, 0xb1, 0xb3, 0xe5, 0x6e, 0x14, 0x66, 0x24, 0x02, 0xc7, 0xf3, 0x1c, 0x86, 0xeb,
	0x7d, 0x4f, 0x94, 0x65, 0x38, 0x1d, 0xe5, 0x9d, 0xee, 0x44, 0xf7, 0x81, 0x33, 0x7a, 0xb5, 0x58,
	0x18, 0xb4, 0x14, 0xce, 0x17, 0xa1, 0x26, 0xe4, 0xf8, 0x0b, 0xac, 0x4a, 0xbb, 0xa4, 0x6c, 0x63,
	0x11, 0xae, 0x08, 0xa5, 0x1a, 0xbe, 0x74, 0xfc, 0x9b, 0x5a, 0x57, 0x06, 0x8f, 0x45, 0xd9, 0xe9,
	0xa2, 0xde, 0x81, 0x28, 0x87, 0xe0, 0x9f, 0x96, 0x48, 0x81, 0xc6, 0x22, 0x98, 0x6b, 0x89, 0xe9,
	0x23, 0x83, 0xcf, 0x02, 0x0b, 0xf9, 0x11, 0x85, 0x1d, 0xf9, 0xf4, 0x4f, 0xf0, 0xb9, 0x75, 0x46,
	0x3d, 0xee, 0x7c, 0xa6, 0x4f, 0x0c, 0x26, 0x7b, 0x4f, 0x6d, 0x09, 0x6f, 0x6b, 0xb0, 0xf7, 0xd7,
	0xf0, 0x4e, 0x17, 0xf4, 0x8f, 0x8b, 0x71, 0x65, 0x90, 0x8d, 0xb6, 0x18, 0xf7, 0x76, 0xbb, 0x09,
	0x2d, 0xb7, 0x5b, 0xe8, 0x6f, 0xff, 0xae, 0x97, 0xff, 0xfa, 0x53, 0xcf, 0x66, 0x21, 0xfd, 0x3a,
	0xbf, 0x5f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x42, 0x81, 0xb8, 0x46, 0x47, 0x03, 0x00, 0x00,
}
