// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: pois-api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestMinerInitParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinerId []byte `protobuf:"bytes,1,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
}

func (x *RequestMinerInitParam) Reset() {
	*x = RequestMinerInitParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pois_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestMinerInitParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMinerInitParam) ProtoMessage() {}

func (x *RequestMinerInitParam) ProtoReflect() protoreflect.Message {
	mi := &file_pois_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMinerInitParam.ProtoReflect.Descriptor instead.
func (*RequestMinerInitParam) Descriptor() ([]byte, []int) {
	return file_pois_api_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMinerInitParam) GetMinerId() []byte {
	if x != nil {
		return x.MinerId
	}
	return nil
}

type ResponseMinerInitParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acc       []byte `protobuf:"bytes,1,opt,name=acc,proto3" json:"acc,omitempty"`                        //init value is from g in RsaKey
	KeyN      []byte `protobuf:"bytes,2,opt,name=key_n,json=keyN,proto3" json:"key_n,omitempty"`          //RsaKey n
	KeyG      []byte `protobuf:"bytes,3,opt,name=key_g,json=keyG,proto3" json:"key_g,omitempty"`          //RsaKey g
	Front     int64  `protobuf:"varint,4,opt,name=front,proto3" json:"front,omitempty"`                   //begin with 0
	Rear      int64  `protobuf:"varint,5,opt,name=rear,proto3" json:"rear,omitempty"`                     //begin with 0
	MinerId   []byte `protobuf:"bytes,6,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"` //miner id
	Signature []byte `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`            //sig all
}

func (x *ResponseMinerInitParam) Reset() {
	*x = ResponseMinerInitParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pois_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseMinerInitParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMinerInitParam) ProtoMessage() {}

func (x *ResponseMinerInitParam) ProtoReflect() protoreflect.Message {
	mi := &file_pois_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMinerInitParam.ProtoReflect.Descriptor instead.
func (*ResponseMinerInitParam) Descriptor() ([]byte, []int) {
	return file_pois_api_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseMinerInitParam) GetAcc() []byte {
	if x != nil {
		return x.Acc
	}
	return nil
}

func (x *ResponseMinerInitParam) GetKeyN() []byte {
	if x != nil {
		return x.KeyN
	}
	return nil
}

func (x *ResponseMinerInitParam) GetKeyG() []byte {
	if x != nil {
		return x.KeyG
	}
	return nil
}

func (x *ResponseMinerInitParam) GetFront() int64 {
	if x != nil {
		return x.Front
	}
	return 0
}

func (x *ResponseMinerInitParam) GetRear() int64 {
	if x != nil {
		return x.Rear
	}
	return 0
}

func (x *ResponseMinerInitParam) GetMinerId() []byte {
	if x != nil {
		return x.MinerId
	}
	return nil
}

func (x *ResponseMinerInitParam) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type RequestMinerCommitGenChall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinerId   []byte         `protobuf:"bytes,1,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	Commit    *Commits       `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	PoisInfo  *MinerPoisInfo `protobuf:"bytes,3,opt,name=pois_info,json=poisInfo,proto3" json:"pois_info,omitempty"`
	MinerSign []byte         `protobuf:"bytes,4,opt,name=miner_sign,json=minerSign,proto3" json:"miner_sign,omitempty"`
}

func (x *RequestMinerCommitGenChall) Reset() {
	*x = RequestMinerCommitGenChall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pois_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestMinerCommitGenChall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMinerCommitGenChall) ProtoMessage() {}

func (x *RequestMinerCommitGenChall) ProtoReflect() protoreflect.Message {
	mi := &file_pois_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMinerCommitGenChall.ProtoReflect.Descriptor instead.
func (*RequestMinerCommitGenChall) Descriptor() ([]byte, []int) {
	return file_pois_api_proto_rawDescGZIP(), []int{2}
}

func (x *RequestMinerCommitGenChall) GetMinerId() []byte {
	if x != nil {
		return x.MinerId
	}
	return nil
}

func (x *RequestMinerCommitGenChall) GetCommit() *Commits {
	if x != nil {
		return x.Commit
	}
	return nil
}

func (x *RequestMinerCommitGenChall) GetPoisInfo() *MinerPoisInfo {
	if x != nil {
		return x.PoisInfo
	}
	return nil
}

func (x *RequestMinerCommitGenChall) GetMinerSign() []byte {
	if x != nil {
		return x.MinerSign
	}
	return nil
}

type Commits struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileIndexs []int64  `protobuf:"varint,1,rep,packed,name=file_indexs,json=fileIndexs,proto3" json:"file_indexs,omitempty"`
	Roots      [][]byte `protobuf:"bytes,2,rep,name=roots,proto3" json:"roots,omitempty"`
}

func (x *Commits) Reset() {
	*x = Commits{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pois_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Commits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commits) ProtoMessage() {}

func (x *Commits) ProtoReflect() protoreflect.Message {
	mi := &file_pois_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commits.ProtoReflect.Descriptor instead.
func (*Commits) Descriptor() ([]byte, []int) {
	return file_pois_api_proto_rawDescGZIP(), []int{3}
}

func (x *Commits) GetFileIndexs() []int64 {
	if x != nil {
		return x.FileIndexs
	}
	return nil
}

func (x *Commits) GetRoots() [][]byte {
	if x != nil {
		return x.Roots
	}
	return nil
}

type MinerPoisInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acc           []byte `protobuf:"bytes,1,opt,name=acc,proto3" json:"acc,omitempty"`
	Front         int64  `protobuf:"varint,2,opt,name=front,proto3" json:"front,omitempty"`
	Rear          int64  `protobuf:"varint,3,opt,name=rear,proto3" json:"rear,omitempty"`
	KeyN          []byte `protobuf:"bytes,4,opt,name=key_n,json=keyN,proto3" json:"key_n,omitempty"`
	KeyG          []byte `protobuf:"bytes,5,opt,name=key_g,json=keyG,proto3" json:"key_g,omitempty"`
	StatusTeeSign []byte `protobuf:"bytes,6,opt,name=status_tee_sign,json=statusTeeSign,proto3" json:"status_tee_sign,omitempty"`
}

func (x *MinerPoisInfo) Reset() {
	*x = MinerPoisInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pois_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinerPoisInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinerPoisInfo) ProtoMessage() {}

func (x *MinerPoisInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pois_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinerPoisInfo.ProtoReflect.Descriptor instead.
func (*MinerPoisInfo) Descriptor() ([]byte, []int) {
	return file_pois_api_proto_rawDescGZIP(), []int{4}
}

func (x *MinerPoisInfo) GetAcc() []byte {
	if x != nil {
		return x.Acc
	}
	return nil
}

func (x *MinerPoisInfo) GetFront() int64 {
	if x != nil {
		return x.Front
	}
	return 0
}

func (x *MinerPoisInfo) GetRear() int64 {
	if x != nil {
		return x.Rear
	}
	return 0
}

func (x *MinerPoisInfo) GetKeyN() []byte {
	if x != nil {
		return x.KeyN
	}
	return nil
}

func (x *MinerPoisInfo) GetKeyG() []byte {
	if x != nil {
		return x.KeyG
	}
	return nil
}

func (x *MinerPoisInfo) GetStatusTeeSign() []byte {
	if x != nil {
		return x.StatusTeeSign
	}
	return nil
}

type Challenge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows         []*Int64Slice `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	ChallTeeSign []byte        `protobuf:"bytes,2,opt,name=chall_tee_sign,json=challTeeSign,proto3" json:"chall_tee_sign,omitempty"`
}

func (x *Challenge) Reset() {
	*x = Challenge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pois_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Challenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Challenge) ProtoMessage() {}

func (x *Challenge) ProtoReflect() protoreflect.Message {
	mi := &file_pois_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Challenge.ProtoReflect.Descriptor instead.
func (*Challenge) Descriptor() ([]byte, []int) {
	return file_pois_api_proto_rawDescGZIP(), []int{5}
}

func (x *Challenge) GetRows() []*Int64Slice {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *Challenge) GetChallTeeSign() []byte {
	if x != nil {
		return x.ChallTeeSign
	}
	return nil
}

type Int64Slice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []int64 `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *Int64Slice) Reset() {
	*x = Int64Slice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pois_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int64Slice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64Slice) ProtoMessage() {}

func (x *Int64Slice) ProtoReflect() protoreflect.Message {
	mi := &file_pois_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64Slice.ProtoReflect.Descriptor instead.
func (*Int64Slice) Descriptor() ([]byte, []int) {
	return file_pois_api_proto_rawDescGZIP(), []int{6}
}

func (x *Int64Slice) GetValues() []int64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type RequestVerifyCommitAndAccProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommitProofGroup *CommitProofGroup `protobuf:"bytes,1,opt,name=commit_proof_group,json=commitProofGroup,proto3" json:"commit_proof_group,omitempty"`
	AccProof         *AccProof         `protobuf:"bytes,2,opt,name=acc_proof,json=accProof,proto3" json:"acc_proof,omitempty"`
	MinerId          []byte            `protobuf:"bytes,3,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	MinerSign        []byte            `protobuf:"bytes,4,opt,name=miner_sign,json=minerSign,proto3" json:"miner_sign,omitempty"`
}

func (x *RequestVerifyCommitAndAccProof) Reset() {
	*x = RequestVerifyCommitAndAccProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pois_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestVerifyCommitAndAccProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVerifyCommitAndAccProof) ProtoMessage() {}

func (x *RequestVerifyCommitAndAccProof) ProtoReflect() protoreflect.Message {
	mi := &file_pois_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVerifyCommitAndAccProof.ProtoReflect.Descriptor instead.
func (*RequestVerifyCommitAndAccProof) Descriptor() ([]byte, []int) {
	return file_pois_api_proto_rawDescGZIP(), []int{7}
}

func (x *RequestVerifyCommitAndAccProof) GetCommitProofGroup() *CommitProofGroup {
	if x != nil {
		return x.CommitProofGroup
	}
	return nil
}

func (x *RequestVerifyCommitAndAccProof) GetAccProof() *AccProof {
	if x != nil {
		return x.AccProof
	}
	return nil
}

func (x *RequestVerifyCommitAndAccProof) GetMinerId() []byte {
	if x != nil {
		return x.MinerId
	}
	return nil
}

func (x *RequestVerifyCommitAndAccProof) GetMinerSign() []byte {
	if x != nil {
		return x.MinerSign
	}
	return nil
}

type CommitProofGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommitProofGroupInner []*CommitProofGroupInner `protobuf:"bytes,1,rep,name=commit_proof_group_inner,json=commitProofGroupInner,proto3" json:"commit_proof_group_inner,omitempty"`
}

func (x *CommitProofGroup) Reset() {
	*x = CommitProofGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pois_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitProofGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitProofGroup) ProtoMessage() {}

func (x *CommitProofGroup) ProtoReflect() protoreflect.Message {
	mi := &file_pois_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitProofGroup.ProtoReflect.Descriptor instead.
func (*CommitProofGroup) Descriptor() ([]byte, []int) {
	return file_pois_api_proto_rawDescGZIP(), []int{8}
}

func (x *CommitProofGroup) GetCommitProofGroupInner() []*CommitProofGroupInner {
	if x != nil {
		return x.CommitProofGroupInner
	}
	return nil
}

type CommitProofGroupInner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommitProof []*CommitProof `protobuf:"bytes,1,rep,name=commit_proof,json=commitProof,proto3" json:"commit_proof,omitempty"`
}

func (x *CommitProofGroupInner) Reset() {
	*x = CommitProofGroupInner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pois_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitProofGroupInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitProofGroupInner) ProtoMessage() {}

func (x *CommitProofGroupInner) ProtoReflect() protoreflect.Message {
	mi := &file_pois_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitProofGroupInner.ProtoReflect.Descriptor instead.
func (*CommitProofGroupInner) Descriptor() ([]byte, []int) {
	return file_pois_api_proto_rawDescGZIP(), []int{9}
}

func (x *CommitProofGroupInner) GetCommitProof() []*CommitProof {
	if x != nil {
		return x.CommitProof
	}
	return nil
}

type CommitProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node    *MhtProof   `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Parents []*MhtProof `protobuf:"bytes,2,rep,name=parents,proto3" json:"parents,omitempty"`
	Elders  []*MhtProof `protobuf:"bytes,3,rep,name=elders,proto3" json:"elders,omitempty"`
}

func (x *CommitProof) Reset() {
	*x = CommitProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pois_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitProof) ProtoMessage() {}

func (x *CommitProof) ProtoReflect() protoreflect.Message {
	mi := &file_pois_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitProof.ProtoReflect.Descriptor instead.
func (*CommitProof) Descriptor() ([]byte, []int) {
	return file_pois_api_proto_rawDescGZIP(), []int{10}
}

func (x *CommitProof) GetNode() *MhtProof {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *CommitProof) GetParents() []*MhtProof {
	if x != nil {
		return x.Parents
	}
	return nil
}

func (x *CommitProof) GetElders() []*MhtProof {
	if x != nil {
		return x.Elders
	}
	return nil
}

type MhtProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Label []byte   `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Paths [][]byte `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
	Locs  []byte   `protobuf:"bytes,4,opt,name=locs,proto3" json:"locs,omitempty"`
}

func (x *MhtProof) Reset() {
	*x = MhtProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pois_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MhtProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MhtProof) ProtoMessage() {}

func (x *MhtProof) ProtoReflect() protoreflect.Message {
	mi := &file_pois_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MhtProof.ProtoReflect.Descriptor instead.
func (*MhtProof) Descriptor() ([]byte, []int) {
	return file_pois_api_proto_rawDescGZIP(), []int{11}
}

func (x *MhtProof) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *MhtProof) GetLabel() []byte {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *MhtProof) GetPaths() [][]byte {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *MhtProof) GetLocs() []byte {
	if x != nil {
		return x.Locs
	}
	return nil
}

type AccProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Indexs    []int64         `protobuf:"varint,1,rep,packed,name=indexs,proto3" json:"indexs,omitempty"`
	Labels    [][]byte        `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	WitChains *AccWitnessNode `protobuf:"bytes,3,opt,name=wit_chains,json=witChains,proto3" json:"wit_chains,omitempty"`
	AccPath   [][]byte        `protobuf:"bytes,4,rep,name=acc_path,json=accPath,proto3" json:"acc_path,omitempty"`
}

func (x *AccProof) Reset() {
	*x = AccProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pois_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccProof) ProtoMessage() {}

func (x *AccProof) ProtoReflect() protoreflect.Message {
	mi := &file_pois_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccProof.ProtoReflect.Descriptor instead.
func (*AccProof) Descriptor() ([]byte, []int) {
	return file_pois_api_proto_rawDescGZIP(), []int{12}
}

func (x *AccProof) GetIndexs() []int64 {
	if x != nil {
		return x.Indexs
	}
	return nil
}

func (x *AccProof) GetLabels() [][]byte {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AccProof) GetWitChains() *AccWitnessNode {
	if x != nil {
		return x.WitChains
	}
	return nil
}

func (x *AccProof) GetAccPath() [][]byte {
	if x != nil {
		return x.AccPath
	}
	return nil
}

type AccWitnessNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Elem []byte          `protobuf:"bytes,1,opt,name=elem,proto3" json:"elem,omitempty"`
	Wit  []byte          `protobuf:"bytes,2,opt,name=wit,proto3" json:"wit,omitempty"`
	Acc  *AccWitnessNode `protobuf:"bytes,3,opt,name=acc,proto3" json:"acc,omitempty"`
}

func (x *AccWitnessNode) Reset() {
	*x = AccWitnessNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pois_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccWitnessNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccWitnessNode) ProtoMessage() {}

func (x *AccWitnessNode) ProtoReflect() protoreflect.Message {
	mi := &file_pois_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccWitnessNode.ProtoReflect.Descriptor instead.
func (*AccWitnessNode) Descriptor() ([]byte, []int) {
	return file_pois_api_proto_rawDescGZIP(), []int{13}
}

func (x *AccWitnessNode) GetElem() []byte {
	if x != nil {
		return x.Elem
	}
	return nil
}

func (x *AccWitnessNode) GetWit() []byte {
	if x != nil {
		return x.Wit
	}
	return nil
}

func (x *AccWitnessNode) GetAcc() *AccWitnessNode {
	if x != nil {
		return x.Acc
	}
	return nil
}

type ResponseVerifyCommitOrDeletionProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PoisStatus     *PoisStatus `protobuf:"bytes,1,opt,name=pois_status,json=poisStatus,proto3" json:"pois_status,omitempty"`
	SignatureAbove []byte      `protobuf:"bytes,2,opt,name=signature_above,json=signatureAbove,proto3" json:"signature_above,omitempty"`
}

func (x *ResponseVerifyCommitOrDeletionProof) Reset() {
	*x = ResponseVerifyCommitOrDeletionProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pois_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseVerifyCommitOrDeletionProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseVerifyCommitOrDeletionProof) ProtoMessage() {}

func (x *ResponseVerifyCommitOrDeletionProof) ProtoReflect() protoreflect.Message {
	mi := &file_pois_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseVerifyCommitOrDeletionProof.ProtoReflect.Descriptor instead.
func (*ResponseVerifyCommitOrDeletionProof) Descriptor() ([]byte, []int) {
	return file_pois_api_proto_rawDescGZIP(), []int{14}
}

func (x *ResponseVerifyCommitOrDeletionProof) GetPoisStatus() *PoisStatus {
	if x != nil {
		return x.PoisStatus
	}
	return nil
}

func (x *ResponseVerifyCommitOrDeletionProof) GetSignatureAbove() []byte {
	if x != nil {
		return x.SignatureAbove
	}
	return nil
}

type PoisStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acc   []byte `protobuf:"bytes,1,opt,name=acc,proto3" json:"acc,omitempty"`
	Front int64  `protobuf:"varint,2,opt,name=front,proto3" json:"front,omitempty"`
	Rear  int64  `protobuf:"varint,3,opt,name=rear,proto3" json:"rear,omitempty"`
}

func (x *PoisStatus) Reset() {
	*x = PoisStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pois_api_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoisStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoisStatus) ProtoMessage() {}

func (x *PoisStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pois_api_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoisStatus.ProtoReflect.Descriptor instead.
func (*PoisStatus) Descriptor() ([]byte, []int) {
	return file_pois_api_proto_rawDescGZIP(), []int{15}
}

func (x *PoisStatus) GetAcc() []byte {
	if x != nil {
		return x.Acc
	}
	return nil
}

func (x *PoisStatus) GetFront() int64 {
	if x != nil {
		return x.Front
	}
	return 0
}

func (x *PoisStatus) GetRear() int64 {
	if x != nil {
		return x.Rear
	}
	return 0
}

type RequestSpaceProofVerify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpaceChals                     []int64        `protobuf:"varint,1,rep,packed,name=space_chals,json=spaceChals,proto3" json:"space_chals,omitempty"`
	MinerId                        []byte         `protobuf:"bytes,2,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	PoisInfo                       *MinerPoisInfo `protobuf:"bytes,3,opt,name=pois_info,json=poisInfo,proto3" json:"pois_info,omitempty"`
	Proof                          *SpaceProof    `protobuf:"bytes,4,opt,name=proof,proto3" json:"proof,omitempty"`
	MinerSpaceProofHashPolkadotSig []byte         `protobuf:"bytes,5,opt,name=miner_space_proof_hash_polkadot_sig,json=minerSpaceProofHashPolkadotSig,proto3" json:"miner_space_proof_hash_polkadot_sig,omitempty"`
}

func (x *RequestSpaceProofVerify) Reset() {
	*x = RequestSpaceProofVerify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pois_api_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestSpaceProofVerify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSpaceProofVerify) ProtoMessage() {}

func (x *RequestSpaceProofVerify) ProtoReflect() protoreflect.Message {
	mi := &file_pois_api_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSpaceProofVerify.ProtoReflect.Descriptor instead.
func (*RequestSpaceProofVerify) Descriptor() ([]byte, []int) {
	return file_pois_api_proto_rawDescGZIP(), []int{16}
}

func (x *RequestSpaceProofVerify) GetSpaceChals() []int64 {
	if x != nil {
		return x.SpaceChals
	}
	return nil
}

func (x *RequestSpaceProofVerify) GetMinerId() []byte {
	if x != nil {
		return x.MinerId
	}
	return nil
}

func (x *RequestSpaceProofVerify) GetPoisInfo() *MinerPoisInfo {
	if x != nil {
		return x.PoisInfo
	}
	return nil
}

func (x *RequestSpaceProofVerify) GetProof() *SpaceProof {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *RequestSpaceProofVerify) GetMinerSpaceProofHashPolkadotSig() []byte {
	if x != nil {
		return x.MinerSpaceProofHashPolkadotSig
	}
	return nil
}

type SpaceProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Left      int64             `protobuf:"varint,1,opt,name=left,proto3" json:"left,omitempty"`
	Right     int64             `protobuf:"varint,2,opt,name=right,proto3" json:"right,omitempty"`
	Proofs    []*MhtProofGroup  `protobuf:"bytes,3,rep,name=proofs,proto3" json:"proofs,omitempty"`
	Roots     [][]byte          `protobuf:"bytes,4,rep,name=roots,proto3" json:"roots,omitempty"`
	WitChains []*AccWitnessNode `protobuf:"bytes,5,rep,name=wit_chains,json=witChains,proto3" json:"wit_chains,omitempty"`
}

func (x *SpaceProof) Reset() {
	*x = SpaceProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pois_api_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceProof) ProtoMessage() {}

func (x *SpaceProof) ProtoReflect() protoreflect.Message {
	mi := &file_pois_api_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceProof.ProtoReflect.Descriptor instead.
func (*SpaceProof) Descriptor() ([]byte, []int) {
	return file_pois_api_proto_rawDescGZIP(), []int{17}
}

func (x *SpaceProof) GetLeft() int64 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *SpaceProof) GetRight() int64 {
	if x != nil {
		return x.Right
	}
	return 0
}

func (x *SpaceProof) GetProofs() []*MhtProofGroup {
	if x != nil {
		return x.Proofs
	}
	return nil
}

func (x *SpaceProof) GetRoots() [][]byte {
	if x != nil {
		return x.Roots
	}
	return nil
}

func (x *SpaceProof) GetWitChains() []*AccWitnessNode {
	if x != nil {
		return x.WitChains
	}
	return nil
}

type ProofHashAndLeftRight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpaceProofHash []byte `protobuf:"bytes,1,opt,name=space_proof_hash,json=spaceProofHash,proto3" json:"space_proof_hash,omitempty"`
	Left           int64  `protobuf:"varint,2,opt,name=left,proto3" json:"left,omitempty"`
	Right          int64  `protobuf:"varint,3,opt,name=right,proto3" json:"right,omitempty"`
	TeeId          []byte `protobuf:"bytes,4,opt,name=tee_id,json=teeId,proto3" json:"tee_id,omitempty"`
}

func (x *ProofHashAndLeftRight) Reset() {
	*x = ProofHashAndLeftRight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pois_api_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProofHashAndLeftRight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProofHashAndLeftRight) ProtoMessage() {}

func (x *ProofHashAndLeftRight) ProtoReflect() protoreflect.Message {
	mi := &file_pois_api_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProofHashAndLeftRight.ProtoReflect.Descriptor instead.
func (*ProofHashAndLeftRight) Descriptor() ([]byte, []int) {
	return file_pois_api_proto_rawDescGZIP(), []int{18}
}

func (x *ProofHashAndLeftRight) GetSpaceProofHash() []byte {
	if x != nil {
		return x.SpaceProofHash
	}
	return nil
}

func (x *ProofHashAndLeftRight) GetLeft() int64 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *ProofHashAndLeftRight) GetRight() int64 {
	if x != nil {
		return x.Right
	}
	return 0
}

func (x *ProofHashAndLeftRight) GetTeeId() []byte {
	if x != nil {
		return x.TeeId
	}
	return nil
}

type MhtProofGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Proofs []*MhtProof `protobuf:"bytes,1,rep,name=proofs,proto3" json:"proofs,omitempty"`
}

func (x *MhtProofGroup) Reset() {
	*x = MhtProofGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pois_api_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MhtProofGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MhtProofGroup) ProtoMessage() {}

func (x *MhtProofGroup) ProtoReflect() protoreflect.Message {
	mi := &file_pois_api_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MhtProofGroup.ProtoReflect.Descriptor instead.
func (*MhtProofGroup) Descriptor() ([]byte, []int) {
	return file_pois_api_proto_rawDescGZIP(), []int{19}
}

func (x *MhtProofGroup) GetProofs() []*MhtProof {
	if x != nil {
		return x.Proofs
	}
	return nil
}

type ResponseSpaceProofVerify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *ResponseSpaceProofVerify) Reset() {
	*x = ResponseSpaceProofVerify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pois_api_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseSpaceProofVerify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseSpaceProofVerify) ProtoMessage() {}

func (x *ResponseSpaceProofVerify) ProtoReflect() protoreflect.Message {
	mi := &file_pois_api_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseSpaceProofVerify.ProtoReflect.Descriptor instead.
func (*ResponseSpaceProofVerify) Descriptor() ([]byte, []int) {
	return file_pois_api_proto_rawDescGZIP(), []int{20}
}

func (x *ResponseSpaceProofVerify) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type RequestSpaceProofVerifyTotal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinerId    []byte         `protobuf:"bytes,1,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	ProofList  []*BlocksProof `protobuf:"bytes,2,rep,name=proof_list,json=proofList,proto3" json:"proof_list,omitempty"`
	Front      int64          `protobuf:"varint,3,opt,name=front,proto3" json:"front,omitempty"`
	Rear       int64          `protobuf:"varint,4,opt,name=rear,proto3" json:"rear,omitempty"`
	Acc        []byte         `protobuf:"bytes,5,opt,name=acc,proto3" json:"acc,omitempty"`
	SpaceChals []int64        `protobuf:"varint,6,rep,packed,name=space_chals,json=spaceChals,proto3" json:"space_chals,omitempty"`
}

func (x *RequestSpaceProofVerifyTotal) Reset() {
	*x = RequestSpaceProofVerifyTotal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pois_api_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestSpaceProofVerifyTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSpaceProofVerifyTotal) ProtoMessage() {}

func (x *RequestSpaceProofVerifyTotal) ProtoReflect() protoreflect.Message {
	mi := &file_pois_api_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSpaceProofVerifyTotal.ProtoReflect.Descriptor instead.
func (*RequestSpaceProofVerifyTotal) Descriptor() ([]byte, []int) {
	return file_pois_api_proto_rawDescGZIP(), []int{21}
}

func (x *RequestSpaceProofVerifyTotal) GetMinerId() []byte {
	if x != nil {
		return x.MinerId
	}
	return nil
}

func (x *RequestSpaceProofVerifyTotal) GetProofList() []*BlocksProof {
	if x != nil {
		return x.ProofList
	}
	return nil
}

func (x *RequestSpaceProofVerifyTotal) GetFront() int64 {
	if x != nil {
		return x.Front
	}
	return 0
}

func (x *RequestSpaceProofVerifyTotal) GetRear() int64 {
	if x != nil {
		return x.Rear
	}
	return 0
}

func (x *RequestSpaceProofVerifyTotal) GetAcc() []byte {
	if x != nil {
		return x.Acc
	}
	return nil
}

func (x *RequestSpaceProofVerifyTotal) GetSpaceChals() []int64 {
	if x != nil {
		return x.SpaceChals
	}
	return nil
}

type BlocksProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProofHashAndLeftRight *ProofHashAndLeftRight `protobuf:"bytes,1,opt,name=proof_hash_and_left_right,json=proofHashAndLeftRight,proto3" json:"proof_hash_and_left_right,omitempty"`
	Signature             []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *BlocksProof) Reset() {
	*x = BlocksProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pois_api_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlocksProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlocksProof) ProtoMessage() {}

func (x *BlocksProof) ProtoReflect() protoreflect.Message {
	mi := &file_pois_api_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlocksProof.ProtoReflect.Descriptor instead.
func (*BlocksProof) Descriptor() ([]byte, []int) {
	return file_pois_api_proto_rawDescGZIP(), []int{22}
}

func (x *BlocksProof) GetProofHashAndLeftRight() *ProofHashAndLeftRight {
	if x != nil {
		return x.ProofHashAndLeftRight
	}
	return nil
}

func (x *BlocksProof) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ResponseSpaceProofVerifyTotalSignatureMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinerId        []byte  `protobuf:"bytes,1,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	TotalProofHash []byte  `protobuf:"bytes,2,opt,name=total_proof_hash,json=totalProofHash,proto3" json:"total_proof_hash,omitempty"`
	Front          int64   `protobuf:"varint,3,opt,name=front,proto3" json:"front,omitempty"`
	Rear           int64   `protobuf:"varint,4,opt,name=rear,proto3" json:"rear,omitempty"`
	Acc            []byte  `protobuf:"bytes,5,opt,name=acc,proto3" json:"acc,omitempty"`
	SpaceChals     []int64 `protobuf:"varint,6,rep,packed,name=space_chals,json=spaceChals,proto3" json:"space_chals,omitempty"`
}

func (x *ResponseSpaceProofVerifyTotalSignatureMember) Reset() {
	*x = ResponseSpaceProofVerifyTotalSignatureMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pois_api_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseSpaceProofVerifyTotalSignatureMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseSpaceProofVerifyTotalSignatureMember) ProtoMessage() {}

func (x *ResponseSpaceProofVerifyTotalSignatureMember) ProtoReflect() protoreflect.Message {
	mi := &file_pois_api_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseSpaceProofVerifyTotalSignatureMember.ProtoReflect.Descriptor instead.
func (*ResponseSpaceProofVerifyTotalSignatureMember) Descriptor() ([]byte, []int) {
	return file_pois_api_proto_rawDescGZIP(), []int{23}
}

func (x *ResponseSpaceProofVerifyTotalSignatureMember) GetMinerId() []byte {
	if x != nil {
		return x.MinerId
	}
	return nil
}

func (x *ResponseSpaceProofVerifyTotalSignatureMember) GetTotalProofHash() []byte {
	if x != nil {
		return x.TotalProofHash
	}
	return nil
}

func (x *ResponseSpaceProofVerifyTotalSignatureMember) GetFront() int64 {
	if x != nil {
		return x.Front
	}
	return 0
}

func (x *ResponseSpaceProofVerifyTotalSignatureMember) GetRear() int64 {
	if x != nil {
		return x.Rear
	}
	return 0
}

func (x *ResponseSpaceProofVerifyTotalSignatureMember) GetAcc() []byte {
	if x != nil {
		return x.Acc
	}
	return nil
}

func (x *ResponseSpaceProofVerifyTotalSignatureMember) GetSpaceChals() []int64 {
	if x != nil {
		return x.SpaceChals
	}
	return nil
}

type ResponseSpaceProofVerifyTotal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinerId    []byte `protobuf:"bytes,1,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	IdleResult bool   `protobuf:"varint,2,opt,name=idle_result,json=idleResult,proto3" json:"idle_result,omitempty"`
	Signature  []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *ResponseSpaceProofVerifyTotal) Reset() {
	*x = ResponseSpaceProofVerifyTotal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pois_api_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseSpaceProofVerifyTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseSpaceProofVerifyTotal) ProtoMessage() {}

func (x *ResponseSpaceProofVerifyTotal) ProtoReflect() protoreflect.Message {
	mi := &file_pois_api_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseSpaceProofVerifyTotal.ProtoReflect.Descriptor instead.
func (*ResponseSpaceProofVerifyTotal) Descriptor() ([]byte, []int) {
	return file_pois_api_proto_rawDescGZIP(), []int{24}
}

func (x *ResponseSpaceProofVerifyTotal) GetMinerId() []byte {
	if x != nil {
		return x.MinerId
	}
	return nil
}

func (x *ResponseSpaceProofVerifyTotal) GetIdleResult() bool {
	if x != nil {
		return x.IdleResult
	}
	return false
}

func (x *ResponseSpaceProofVerifyTotal) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type RequestVerifyDeletionProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roots     [][]byte        `protobuf:"bytes,1,rep,name=roots,proto3" json:"roots,omitempty"`
	WitChain  *AccWitnessNode `protobuf:"bytes,2,opt,name=wit_chain,json=witChain,proto3" json:"wit_chain,omitempty"`
	AccPath   [][]byte        `protobuf:"bytes,3,rep,name=acc_path,json=accPath,proto3" json:"acc_path,omitempty"`
	MinerId   []byte          `protobuf:"bytes,4,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	PoisInfo  *MinerPoisInfo  `protobuf:"bytes,5,opt,name=pois_info,json=poisInfo,proto3" json:"pois_info,omitempty"`
	MinerSign []byte          `protobuf:"bytes,6,opt,name=miner_sign,json=minerSign,proto3" json:"miner_sign,omitempty"`
}

func (x *RequestVerifyDeletionProof) Reset() {
	*x = RequestVerifyDeletionProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pois_api_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestVerifyDeletionProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVerifyDeletionProof) ProtoMessage() {}

func (x *RequestVerifyDeletionProof) ProtoReflect() protoreflect.Message {
	mi := &file_pois_api_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVerifyDeletionProof.ProtoReflect.Descriptor instead.
func (*RequestVerifyDeletionProof) Descriptor() ([]byte, []int) {
	return file_pois_api_proto_rawDescGZIP(), []int{25}
}

func (x *RequestVerifyDeletionProof) GetRoots() [][]byte {
	if x != nil {
		return x.Roots
	}
	return nil
}

func (x *RequestVerifyDeletionProof) GetWitChain() *AccWitnessNode {
	if x != nil {
		return x.WitChain
	}
	return nil
}

func (x *RequestVerifyDeletionProof) GetAccPath() [][]byte {
	if x != nil {
		return x.AccPath
	}
	return nil
}

func (x *RequestVerifyDeletionProof) GetMinerId() []byte {
	if x != nil {
		return x.MinerId
	}
	return nil
}

func (x *RequestVerifyDeletionProof) GetPoisInfo() *MinerPoisInfo {
	if x != nil {
		return x.PoisInfo
	}
	return nil
}

func (x *RequestVerifyDeletionProof) GetMinerSign() []byte {
	if x != nil {
		return x.MinerSign
	}
	return nil
}

var File_pois_api_proto protoreflect.FileDescriptor

var file_pois_api_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x6f, 0x69, 0x73, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x6f, 0x69, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x22, 0x32, 0x0a, 0x15, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x69, 0x74, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x22, 0xb7,
	0x01, 0x0a, 0x16, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x69, 0x6e, 0x65, 0x72,
	0x49, 0x6e, 0x69, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x63,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x61, 0x63, 0x63, 0x12, 0x13, 0x0a, 0x05, 0x6b,
	0x65, 0x79, 0x5f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x4e,
	0x12, 0x13, 0x0a, 0x05, 0x6b, 0x65, 0x79, 0x5f, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x6b, 0x65, 0x79, 0x47, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x65, 0x61, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x72, 0x65, 0x61, 0x72, 0x12,
	0x19, 0x0a, 0x08, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0xb7, 0x01, 0x0a, 0x1a, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x4d, 0x69, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x47,
	0x65, 0x6e, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x69, 0x6e, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x29, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x6f, 0x69, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x73, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x34, 0x0a,
	0x09, 0x70, 0x6f, 0x69, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x70, 0x6f, 0x69, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x69, 0x6e, 0x65,
	0x72, 0x50, 0x6f, 0x69, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x70, 0x6f, 0x69, 0x73, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x73, 0x69, 0x67,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x69,
	0x67, 0x6e, 0x22, 0x40, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x12, 0x1f, 0x0a,
	0x0b, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x03, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x72,
	0x6f, 0x6f, 0x74, 0x73, 0x22, 0x9d, 0x01, 0x0a, 0x0d, 0x4d, 0x69, 0x6e, 0x65, 0x72, 0x50, 0x6f,
	0x69, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x63, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x61, 0x63, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x72, 0x6f, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x72, 0x65, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x72, 0x65,
	0x61, 0x72, 0x12, 0x13, 0x0a, 0x05, 0x6b, 0x65, 0x79, 0x5f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x4e, 0x12, 0x13, 0x0a, 0x05, 0x6b, 0x65, 0x79, 0x5f, 0x67,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x47, 0x12, 0x26, 0x0a, 0x0f,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x74, 0x65, 0x65, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x65, 0x65,
	0x53, 0x69, 0x67, 0x6e, 0x22, 0x5b, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x12, 0x28, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x70, 0x6f, 0x69, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x74, 0x36, 0x34,
	0x53, 0x6c, 0x69, 0x63, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x63,
	0x68, 0x61, 0x6c, 0x6c, 0x5f, 0x74, 0x65, 0x65, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0c, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x54, 0x65, 0x65, 0x53, 0x69, 0x67,
	0x6e, 0x22, 0x24, 0x0a, 0x0a, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0xd5, 0x01, 0x0a, 0x1e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x41,
	0x6e, 0x64, 0x41, 0x63, 0x63, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x48, 0x0a, 0x12, 0x63, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x6f, 0x69, 0x73, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x10, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x12, 0x2f, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x6f,
	0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x6f, 0x69, 0x73, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x41, 0x63, 0x63, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x08, 0x61, 0x63, 0x63,
	0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x22,
	0x6c, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x12, 0x58, 0x0a, 0x18, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x70, 0x72,
	0x6f, 0x6f, 0x66, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x6f, 0x69, 0x73, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x15, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x50, 0x72,
	0x6f, 0x6f, 0x66, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x22, 0x51, 0x0a,
	0x15, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70,
	0x6f, 0x69, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x50, 0x72,
	0x6f, 0x6f, 0x66, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66,
	0x22, 0x8f, 0x01, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66,
	0x12, 0x26, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x70, 0x6f, 0x69, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x68, 0x74, 0x50, 0x72, 0x6f,
	0x6f, 0x66, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x6f, 0x69, 0x73,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x68, 0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x07, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x2a, 0x0a, 0x06, 0x65, 0x6c, 0x64, 0x65, 0x72, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x6f, 0x69, 0x73, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x4d, 0x68, 0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x06, 0x65, 0x6c, 0x64, 0x65,
	0x72, 0x73, 0x22, 0x60, 0x0a, 0x08, 0x4d, 0x68, 0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61,
	0x74, 0x68, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x63, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x6c, 0x6f, 0x63, 0x73, 0x22, 0x8e, 0x01, 0x0a, 0x08, 0x41, 0x63, 0x63, 0x50, 0x72, 0x6f, 0x6f,
	0x66, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x06, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x73, 0x12, 0x37, 0x0a, 0x0a, 0x77, 0x69, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x6f, 0x69, 0x73, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x41, 0x63, 0x63, 0x57, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x09, 0x77, 0x69, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x63,
	0x63, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x63,
	0x63, 0x50, 0x61, 0x74, 0x68, 0x22, 0x62, 0x0a, 0x0e, 0x41, 0x63, 0x63, 0x57, 0x69, 0x74, 0x6e,
	0x65, 0x73, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x6c, 0x65, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x65, 0x6c, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x77,
	0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x77, 0x69, 0x74, 0x12, 0x2a, 0x0a,
	0x03, 0x61, 0x63, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x6f, 0x69,
	0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x63, 0x63, 0x57, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73,
	0x4e, 0x6f, 0x64, 0x65, 0x52, 0x03, 0x61, 0x63, 0x63, 0x22, 0x85, 0x01, 0x0a, 0x23, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x4f, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x6f,
	0x66, 0x12, 0x35, 0x0a, 0x0b, 0x70, 0x6f, 0x69, 0x73, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x6f, 0x69, 0x73, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x50, 0x6f, 0x69, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0a, 0x70, 0x6f,
	0x69, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x61, 0x62, 0x6f, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x41, 0x62, 0x6f, 0x76,
	0x65, 0x22, 0x48, 0x0a, 0x0a, 0x50, 0x6f, 0x69, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x61, 0x63, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x61, 0x63,
	0x63, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x61, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x72, 0x65, 0x61, 0x72, 0x22, 0x84, 0x02, 0x0a, 0x17,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x6f,
	0x66, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x5f, 0x63, 0x68, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6c, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x69, 0x6e, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x09, 0x70, 0x6f, 0x69, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x6f, 0x69, 0x73, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x4d, 0x69, 0x6e, 0x65, 0x72, 0x50, 0x6f, 0x69, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x08, 0x70, 0x6f, 0x69, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2a, 0x0a, 0x05, 0x70, 0x72, 0x6f,
	0x6f, 0x66, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x6f, 0x69, 0x73, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x05,
	0x70, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x4b, 0x0a, 0x23, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x5f,
	0x70, 0x6f, 0x6c, 0x6b, 0x61, 0x64, 0x6f, 0x74, 0x5f, 0x73, 0x69, 0x67, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x1e, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x50, 0x72,
	0x6f, 0x6f, 0x66, 0x48, 0x61, 0x73, 0x68, 0x50, 0x6f, 0x6c, 0x6b, 0x61, 0x64, 0x6f, 0x74, 0x53,
	0x69, 0x67, 0x22, 0xb6, 0x01, 0x0a, 0x0a, 0x53, 0x70, 0x61, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x6f,
	0x66, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x6c, 0x65, 0x66, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x12, 0x2f, 0x0a, 0x06, 0x70,
	0x72, 0x6f, 0x6f, 0x66, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x6f,
	0x69, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x68, 0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x72, 0x6f, 0x6f, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x72, 0x6f, 0x6f,
	0x74, 0x73, 0x12, 0x37, 0x0a, 0x0a, 0x77, 0x69, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x6f, 0x69, 0x73, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x41, 0x63, 0x63, 0x57, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x09, 0x77, 0x69, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x22, 0x82, 0x01, 0x0a, 0x15,
	0x50, 0x72, 0x6f, 0x6f, 0x66, 0x48, 0x61, 0x73, 0x68, 0x41, 0x6e, 0x64, 0x4c, 0x65, 0x66, 0x74,
	0x52, 0x69, 0x67, 0x68, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x70,
	0x72, 0x6f, 0x6f, 0x66, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x48, 0x61, 0x73, 0x68, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6c,
	0x65, 0x66, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x65, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x74, 0x65, 0x65, 0x49, 0x64,
	0x22, 0x3b, 0x0a, 0x0d, 0x4d, 0x68, 0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x12, 0x2a, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x70, 0x6f, 0x69, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x68, 0x74,
	0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x73, 0x22, 0x38, 0x0a,
	0x18, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x50, 0x72,
	0x6f, 0x6f, 0x66, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0xcc, 0x01, 0x0a, 0x1c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x69, 0x6e, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x6f, 0x69, 0x73, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x09,
	0x70, 0x72, 0x6f, 0x6f, 0x66, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x72, 0x6f,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x72, 0x65, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x72,
	0x65, 0x61, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x61, 0x63, 0x63, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x63,
	0x68, 0x61, 0x6c, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x43, 0x68, 0x61, 0x6c, 0x73, 0x22, 0x86, 0x01, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x73, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x59, 0x0a, 0x19, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x5f,
	0x68, 0x61, 0x73, 0x68, 0x5f, 0x61, 0x6e, 0x64, 0x5f, 0x6c, 0x65, 0x66, 0x74, 0x5f, 0x72, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x6f, 0x69, 0x73,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x48, 0x61, 0x73, 0x68, 0x41, 0x6e,
	0x64, 0x4c, 0x65, 0x66, 0x74, 0x52, 0x69, 0x67, 0x68, 0x74, 0x52, 0x15, 0x70, 0x72, 0x6f, 0x6f,
	0x66, 0x48, 0x61, 0x73, 0x68, 0x41, 0x6e, 0x64, 0x4c, 0x65, 0x66, 0x74, 0x52, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22,
	0xd0, 0x01, 0x0a, 0x2c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x19, 0x0a, 0x08, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x6f,
	0x66, 0x48, 0x61, 0x73, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x65, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x72, 0x65, 0x61, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x61, 0x63, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x61, 0x63,
	0x63, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x6c, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x70, 0x61, 0x63, 0x65, 0x43, 0x68, 0x61,
	0x6c, 0x73, 0x22, 0x79, 0x0a, 0x1d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x69, 0x64, 0x6c, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0xf4, 0x01,
	0x0a, 0x1a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x14, 0x0a, 0x05,
	0x72, 0x6f, 0x6f, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x72, 0x6f, 0x6f,
	0x74, 0x73, 0x12, 0x35, 0x0a, 0x09, 0x77, 0x69, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x6f, 0x69, 0x73, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x41, 0x63, 0x63, 0x57, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x08, 0x77, 0x69, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x63, 0x63,
	0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x63, 0x63,
	0x50, 0x61, 0x74, 0x68, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x34, 0x0a, 0x09, 0x70, 0x6f, 0x69, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x6f, 0x69, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x69,
	0x6e, 0x65, 0x72, 0x50, 0x6f, 0x69, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x70, 0x6f, 0x69,
	0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x73,
	0x69, 0x67, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x6d, 0x69, 0x6e, 0x65, 0x72,
	0x53, 0x69, 0x67, 0x6e, 0x32, 0xa1, 0x05, 0x0a, 0x07, 0x50, 0x6f, 0x69, 0x73, 0x41, 0x70, 0x69,
	0x12, 0x60, 0x0a, 0x19, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x6d, 0x69, 0x6e, 0x65,
	0x72, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x6e, 0x65, 0x77, 0x5f, 0x6b, 0x65, 0x79, 0x12, 0x1f, 0x2e,
	0x70, 0x6f, 0x69, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x4d, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x69, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x20,
	0x2e, 0x70, 0x6f, 0x69, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x4d, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x69, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x22, 0x00, 0x12, 0x5d, 0x0a, 0x1e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x6d, 0x69,
	0x6e, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x67, 0x65, 0x6e, 0x5f, 0x63,
	0x68, 0x61, 0x6c, 0x6c, 0x12, 0x24, 0x2e, 0x70, 0x6f, 0x69, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x69, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x47, 0x65, 0x6e, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x1a, 0x13, 0x2e, 0x70, 0x6f, 0x69,
	0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x22,
	0x00, 0x12, 0x78, 0x0a, 0x1b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x76, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66,
	0x12, 0x28, 0x2e, 0x70, 0x6f, 0x69, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x41,
	0x6e, 0x64, 0x41, 0x63, 0x63, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x1a, 0x2d, 0x2e, 0x70, 0x6f, 0x69,
	0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x4f, 0x72, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x22, 0x00, 0x12, 0x72, 0x0a, 0x27, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x70, 0x72, 0x6f,
	0x6f, 0x66, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x5f, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65,
	0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x21, 0x2e, 0x70, 0x6f, 0x69, 0x73, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x50, 0x72,
	0x6f, 0x6f, 0x66, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x1a, 0x22, 0x2e, 0x70, 0x6f, 0x69, 0x73,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x22, 0x00, 0x12,
	0x6f, 0x0a, 0x1a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x5f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x26, 0x2e,
	0x70, 0x6f, 0x69, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x1a, 0x27, 0x2e, 0x70, 0x6f, 0x69, 0x73, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x50, 0x72,
	0x6f, 0x6f, 0x66, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x00,
	0x12, 0x76, 0x0a, 0x1d, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x6f,
	0x66, 0x12, 0x24, 0x2e, 0x70, 0x6f, 0x69, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x69,
	0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x1a, 0x2d, 0x2e, 0x70, 0x6f, 0x69, 0x73, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x4f, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pois_api_proto_rawDescOnce sync.Once
	file_pois_api_proto_rawDescData = file_pois_api_proto_rawDesc
)

func file_pois_api_proto_rawDescGZIP() []byte {
	file_pois_api_proto_rawDescOnce.Do(func() {
		file_pois_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_pois_api_proto_rawDescData)
	})
	return file_pois_api_proto_rawDescData
}

var file_pois_api_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_pois_api_proto_goTypes = []interface{}{
	(*RequestMinerInitParam)(nil),                        // 0: pois.api.RequestMinerInitParam
	(*ResponseMinerInitParam)(nil),                       // 1: pois.api.ResponseMinerInitParam
	(*RequestMinerCommitGenChall)(nil),                   // 2: pois.api.RequestMinerCommitGenChall
	(*Commits)(nil),                                      // 3: pois.api.Commits
	(*MinerPoisInfo)(nil),                                // 4: pois.api.MinerPoisInfo
	(*Challenge)(nil),                                    // 5: pois.api.Challenge
	(*Int64Slice)(nil),                                   // 6: pois.api.Int64Slice
	(*RequestVerifyCommitAndAccProof)(nil),               // 7: pois.api.RequestVerifyCommitAndAccProof
	(*CommitProofGroup)(nil),                             // 8: pois.api.CommitProofGroup
	(*CommitProofGroupInner)(nil),                        // 9: pois.api.CommitProofGroupInner
	(*CommitProof)(nil),                                  // 10: pois.api.CommitProof
	(*MhtProof)(nil),                                     // 11: pois.api.MhtProof
	(*AccProof)(nil),                                     // 12: pois.api.AccProof
	(*AccWitnessNode)(nil),                               // 13: pois.api.AccWitnessNode
	(*ResponseVerifyCommitOrDeletionProof)(nil),          // 14: pois.api.ResponseVerifyCommitOrDeletionProof
	(*PoisStatus)(nil),                                   // 15: pois.api.PoisStatus
	(*RequestSpaceProofVerify)(nil),                      // 16: pois.api.RequestSpaceProofVerify
	(*SpaceProof)(nil),                                   // 17: pois.api.SpaceProof
	(*ProofHashAndLeftRight)(nil),                        // 18: pois.api.ProofHashAndLeftRight
	(*MhtProofGroup)(nil),                                // 19: pois.api.MhtProofGroup
	(*ResponseSpaceProofVerify)(nil),                     // 20: pois.api.ResponseSpaceProofVerify
	(*RequestSpaceProofVerifyTotal)(nil),                 // 21: pois.api.RequestSpaceProofVerifyTotal
	(*BlocksProof)(nil),                                  // 22: pois.api.BlocksProof
	(*ResponseSpaceProofVerifyTotalSignatureMember)(nil), // 23: pois.api.ResponseSpaceProofVerifyTotalSignatureMember
	(*ResponseSpaceProofVerifyTotal)(nil),                // 24: pois.api.ResponseSpaceProofVerifyTotal
	(*RequestVerifyDeletionProof)(nil),                   // 25: pois.api.RequestVerifyDeletionProof
}
var file_pois_api_proto_depIdxs = []int32{
	3,  // 0: pois.api.RequestMinerCommitGenChall.commit:type_name -> pois.api.Commits
	4,  // 1: pois.api.RequestMinerCommitGenChall.pois_info:type_name -> pois.api.MinerPoisInfo
	6,  // 2: pois.api.Challenge.rows:type_name -> pois.api.Int64Slice
	8,  // 3: pois.api.RequestVerifyCommitAndAccProof.commit_proof_group:type_name -> pois.api.CommitProofGroup
	12, // 4: pois.api.RequestVerifyCommitAndAccProof.acc_proof:type_name -> pois.api.AccProof
	9,  // 5: pois.api.CommitProofGroup.commit_proof_group_inner:type_name -> pois.api.CommitProofGroupInner
	10, // 6: pois.api.CommitProofGroupInner.commit_proof:type_name -> pois.api.CommitProof
	11, // 7: pois.api.CommitProof.node:type_name -> pois.api.MhtProof
	11, // 8: pois.api.CommitProof.parents:type_name -> pois.api.MhtProof
	11, // 9: pois.api.CommitProof.elders:type_name -> pois.api.MhtProof
	13, // 10: pois.api.AccProof.wit_chains:type_name -> pois.api.AccWitnessNode
	13, // 11: pois.api.AccWitnessNode.acc:type_name -> pois.api.AccWitnessNode
	15, // 12: pois.api.ResponseVerifyCommitOrDeletionProof.pois_status:type_name -> pois.api.PoisStatus
	4,  // 13: pois.api.RequestSpaceProofVerify.pois_info:type_name -> pois.api.MinerPoisInfo
	17, // 14: pois.api.RequestSpaceProofVerify.proof:type_name -> pois.api.SpaceProof
	19, // 15: pois.api.SpaceProof.proofs:type_name -> pois.api.MhtProofGroup
	13, // 16: pois.api.SpaceProof.wit_chains:type_name -> pois.api.AccWitnessNode
	11, // 17: pois.api.MhtProofGroup.proofs:type_name -> pois.api.MhtProof
	22, // 18: pois.api.RequestSpaceProofVerifyTotal.proof_list:type_name -> pois.api.BlocksProof
	18, // 19: pois.api.BlocksProof.proof_hash_and_left_right:type_name -> pois.api.ProofHashAndLeftRight
	13, // 20: pois.api.RequestVerifyDeletionProof.wit_chain:type_name -> pois.api.AccWitnessNode
	4,  // 21: pois.api.RequestVerifyDeletionProof.pois_info:type_name -> pois.api.MinerPoisInfo
	0,  // 22: pois.api.PoisApi.request_miner_get_new_key:input_type -> pois.api.RequestMinerInitParam
	2,  // 23: pois.api.PoisApi.request_miner_commit_gen_chall:input_type -> pois.api.RequestMinerCommitGenChall
	7,  // 24: pois.api.PoisApi.request_verify_commit_proof:input_type -> pois.api.RequestVerifyCommitAndAccProof
	16, // 25: pois.api.PoisApi.request_space_proof_verify_single_block:input_type -> pois.api.RequestSpaceProofVerify
	21, // 26: pois.api.PoisApi.request_verify_space_total:input_type -> pois.api.RequestSpaceProofVerifyTotal
	25, // 27: pois.api.PoisApi.request_verify_deletion_proof:input_type -> pois.api.RequestVerifyDeletionProof
	1,  // 28: pois.api.PoisApi.request_miner_get_new_key:output_type -> pois.api.ResponseMinerInitParam
	5,  // 29: pois.api.PoisApi.request_miner_commit_gen_chall:output_type -> pois.api.Challenge
	14, // 30: pois.api.PoisApi.request_verify_commit_proof:output_type -> pois.api.ResponseVerifyCommitOrDeletionProof
	20, // 31: pois.api.PoisApi.request_space_proof_verify_single_block:output_type -> pois.api.ResponseSpaceProofVerify
	24, // 32: pois.api.PoisApi.request_verify_space_total:output_type -> pois.api.ResponseSpaceProofVerifyTotal
	14, // 33: pois.api.PoisApi.request_verify_deletion_proof:output_type -> pois.api.ResponseVerifyCommitOrDeletionProof
	28, // [28:34] is the sub-list for method output_type
	22, // [22:28] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_pois_api_proto_init() }
func file_pois_api_proto_init() {
	if File_pois_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pois_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestMinerInitParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pois_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseMinerInitParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pois_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestMinerCommitGenChall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pois_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Commits); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pois_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinerPoisInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pois_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Challenge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pois_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Int64Slice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pois_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestVerifyCommitAndAccProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pois_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitProofGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pois_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitProofGroupInner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pois_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pois_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MhtProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pois_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pois_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccWitnessNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pois_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseVerifyCommitOrDeletionProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pois_api_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoisStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pois_api_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestSpaceProofVerify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pois_api_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pois_api_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProofHashAndLeftRight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pois_api_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MhtProofGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pois_api_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseSpaceProofVerify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pois_api_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestSpaceProofVerifyTotal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pois_api_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlocksProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pois_api_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseSpaceProofVerifyTotalSignatureMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pois_api_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseSpaceProofVerifyTotal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pois_api_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestVerifyDeletionProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pois_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pois_api_proto_goTypes,
		DependencyIndexes: file_pois_api_proto_depIdxs,
		MessageInfos:      file_pois_api_proto_msgTypes,
	}.Build()
	File_pois_api_proto = out.File
	file_pois_api_proto_rawDesc = nil
	file_pois_api_proto_goTypes = nil
	file_pois_api_proto_depIdxs = nil
}
