// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: proof.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Qslice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	I int64  `protobuf:"varint,1,opt,name=i,proto3" json:"i,omitempty"`
	V string `protobuf:"bytes,2,opt,name=v,proto3" json:"v,omitempty"`
}

func (x *Qslice) Reset() {
	*x = Qslice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proof_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Qslice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Qslice) ProtoMessage() {}

func (x *Qslice) ProtoReflect() protoreflect.Message {
	mi := &file_proof_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Qslice.ProtoReflect.Descriptor instead.
func (*Qslice) Descriptor() ([]byte, []int) {
	return file_proof_proto_rawDescGZIP(), []int{0}
}

func (x *Qslice) GetI() int64 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *Qslice) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

// a protocol define a set of reuqest and responses
type AggrProofRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdleProofFileHash    string    `protobuf:"bytes,1,opt,name=idle_proof_file_hash,json=idleProofFileHash,proto3" json:"idle_proof_file_hash,omitempty"`
	ServiceProofFileHash string    `protobuf:"bytes,2,opt,name=service_proof_file_hash,json=serviceProofFileHash,proto3" json:"service_proof_file_hash,omitempty"`
	Qslice               []*Qslice `protobuf:"bytes,3,rep,name=qslice,proto3" json:"qslice,omitempty"`
	Publickey            []byte    `protobuf:"bytes,4,opt,name=publickey,proto3" json:"publickey,omitempty"`
	Sign                 []byte    `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (x *AggrProofRequest) Reset() {
	*x = AggrProofRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proof_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AggrProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggrProofRequest) ProtoMessage() {}

func (x *AggrProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proof_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggrProofRequest.ProtoReflect.Descriptor instead.
func (*AggrProofRequest) Descriptor() ([]byte, []int) {
	return file_proof_proto_rawDescGZIP(), []int{1}
}

func (x *AggrProofRequest) GetIdleProofFileHash() string {
	if x != nil {
		return x.IdleProofFileHash
	}
	return ""
}

func (x *AggrProofRequest) GetServiceProofFileHash() string {
	if x != nil {
		return x.ServiceProofFileHash
	}
	return ""
}

func (x *AggrProofRequest) GetQslice() []*Qslice {
	if x != nil {
		return x.Qslice
	}
	return nil
}

func (x *AggrProofRequest) GetPublickey() []byte {
	if x != nil {
		return x.Publickey
	}
	return nil
}

func (x *AggrProofRequest) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

type AggrProofResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code uint32 `protobuf:"varint,1,opt,name=Code,json=code,proto3" json:"Code,omitempty"`
}

func (x *AggrProofResponse) Reset() {
	*x = AggrProofResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proof_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AggrProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggrProofResponse) ProtoMessage() {}

func (x *AggrProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proof_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggrProofResponse.ProtoReflect.Descriptor instead.
func (*AggrProofResponse) Descriptor() ([]byte, []int) {
	return file_proof_proto_rawDescGZIP(), []int{2}
}

func (x *AggrProofResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_proof_proto protoreflect.FileDescriptor

var file_proof_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a,
	0x06, 0x51, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x69, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x01, 0x69, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x01, 0x76, 0x22, 0xcd, 0x01, 0x0a, 0x10, 0x41, 0x67, 0x67, 0x72, 0x50, 0x72, 0x6f, 0x6f,
	0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x14, 0x69, 0x64, 0x6c, 0x65,
	0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x68, 0x61, 0x73, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x69, 0x64, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x6f,
	0x66, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x61, 0x73, 0x68, 0x12, 0x35, 0x0a, 0x17, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x1f, 0x0a, 0x06, 0x71, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x07, 0x2e, 0x51, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x52, 0x06, 0x71, 0x73, 0x6c, 0x69, 0x63,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x6b, 0x65, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x6b, 0x65, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73,
	0x69, 0x67, 0x6e, 0x22, 0x27, 0x0a, 0x11, 0x41, 0x67, 0x67, 0x72, 0x50, 0x72, 0x6f, 0x6f, 0x66,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x07, 0x5a, 0x05,
	0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proof_proto_rawDescOnce sync.Once
	file_proof_proto_rawDescData = file_proof_proto_rawDesc
)

func file_proof_proto_rawDescGZIP() []byte {
	file_proof_proto_rawDescOnce.Do(func() {
		file_proof_proto_rawDescData = protoimpl.X.CompressGZIP(file_proof_proto_rawDescData)
	})
	return file_proof_proto_rawDescData
}

var file_proof_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proof_proto_goTypes = []interface{}{
	(*Qslice)(nil),            // 0: Qslice
	(*AggrProofRequest)(nil),  // 1: AggrProofRequest
	(*AggrProofResponse)(nil), // 2: AggrProofResponse
}
var file_proof_proto_depIdxs = []int32{
	0, // 0: AggrProofRequest.qslice:type_name -> Qslice
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proof_proto_init() }
func file_proof_proto_init() {
	if File_proof_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proof_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Qslice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proof_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AggrProofRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proof_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AggrProofResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proof_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proof_proto_goTypes,
		DependencyIndexes: file_proof_proto_depIdxs,
		MessageInfos:      file_proof_proto_msgTypes,
	}.Build()
	File_proof_proto = out.File
	file_proof_proto_rawDesc = nil
	file_proof_proto_goTypes = nil
	file_proof_proto_depIdxs = nil
}
